<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-26T11:38:48 IST" name="Default suite" finished-at="2021-08-26T11:39:56 IST" duration-ms="67525">
    <groups>
    </groups>
    <test started-at="2021-08-26T11:38:48 IST" name="Default test" finished-at="2021-08-26T11:39:56 IST" duration-ms="67525">
      <class name="testcase.Assessment1">
        <test-method is-config="true" signature="setFileName()[pri:0, instance:testcase.Assessment1@73a1e9a9]" started-at="2021-08-26T11:38:49 IST" name="setFileName" finished-at="2021-08-26T11:38:49 IST" duration-ms="22" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setFileName -->
        <test-method is-config="true" signature="preCondition()[pri:0, instance:testcase.Assessment1@73a1e9a9]" started-at="2021-08-26T11:38:50 IST" name="preCondition" finished-at="2021-08-26T11:38:56 IST" duration-ms="6495" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method signature="createAssessment(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testcase.Assessment1@73a1e9a9]" started-at="2021-08-26T11:38:56 IST" name="createAssessment" data-provider="fetchData" finished-at="2021-08-26T11:39:55 IST" duration-ms="59048" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Call/Email/Meeting]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[makaia@testleaf.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SelBootcamp$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index -1 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:359)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at pages.HomePage.getAppAndDeveloperName(HomePage.java:41)
at testcase.Assessment1.createAssessment(Assessment1.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAssessment -->
        <test-method is-config="true" signature="postCondition()[pri:0, instance:testcase.Assessment1@73a1e9a9]" started-at="2021-08-26T11:39:55 IST" name="postCondition" finished-at="2021-08-26T11:39:56 IST" duration-ms="653" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
      </class> <!-- testcase.Assessment1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
